version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:5173:5173"
    depends_on:
      - backend
    networks:
      - frontend_net
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:8888:8888"
    depends_on:
      - database
      - cache
    networks:
      - backend_net
      - data_net
    secrets:
      - db_user
      - db_password
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: XXXXXXXXXXXXXXXXXXX
      MYSQL_DATABASE: clothes_store
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_SSL_CA: /etc/mysql/certs/mysql-ca.pem
      MYSQL_SSL_CERT: /etc/mysql/certs/mysql-server.crt
      MYSQL_SSL_KEY: /etc/mysql/certs/mysql-server.key
      TZ: "Europe/Kiev"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/certs:/etc/mysql/certs
      - ./database/clothes_store.sql:/docker-entrypoint-initdb.d/clothes_store.sql
    ports:
      - "127.0.0.1:3307:3306"
    networks:
      - data_net
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"
        reservations:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cache:
    image: redis:latest
    ports:
      - "127.0.0.1:6380:6379"
    networks:
      - data_net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  proxy:
    build:
      context: ./proxy
    ports:
      - "8080:443"
    depends_on:
      - frontend
      - backend
    networks:
      - backend_net
      - frontend_net
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge
  data_net:
    driver: bridge


secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
